"""
Deterministic funnel analysis engine (stage-agnostic).

All numbers in the final report come from here — they are computed, never
generated by the LLM. Given application/event rows where each stage has a
timestamp column (non-empty = stage reached), it computes counts, step
conversion / drop-off, overall conversion, stage velocity, and segment
breakdowns.
"""
from __future__ import annotations

import csv
import statistics
from datetime import datetime
from typing import Optional


_TS_FORMATS = ("%Y-%m-%d %H:%M", "%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S")


def parse_ts(v: Optional[str]) -> Optional[datetime]:
    v = (v or "").strip()
    if not v:
        return None
    for fmt in _TS_FORMATS:
        try:
            return datetime.strptime(v, fmt)
        except ValueError:
            continue
    return None


def load_rows(path: str) -> list[dict]:
    with open(path, newline="") as fp:
        return list(csv.DictReader(fp))


def _pct(n: int, d: int) -> float:
    return round(100.0 * n / d, 2) if d else 0.0


class FunnelAnalyzer:
    def __init__(self, stages: list[dict], segment_dimensions: list[str],
                 funnel_name: str = "Funnel"):
        # stages: [{"key","label","ts_column"}], ordered top -> bottom
        self.stages = stages
        self.segment_dimensions = segment_dimensions
        self.funnel_name = funnel_name

    def _reached(self, row: dict, stage: dict) -> bool:
        return parse_ts(row.get(stage["ts_column"])) is not None

    def _counts(self, rows: list[dict]) -> dict:
        return {s["key"]: sum(1 for r in rows if self._reached(r, s))
                for s in self.stages}

    def build_funnel(self, rows: list[dict]) -> dict:
        counts = self._counts(rows)
        top = counts[self.stages[0]["key"]] or 1
        steps = []
        for i, s in enumerate(self.stages):
            prev_key = self.stages[i - 1]["key"] if i > 0 else None
            prev = counts[prev_key] if prev_key else None
            steps.append({
                "stage": s["label"],
                "count": counts[s["key"]],
                "pct_of_top": _pct(counts[s["key"]], top),
                "step_conversion_pct": _pct(counts[s["key"]], prev) if prev else None,
                "step_dropoff_pct": round(100 - _pct(counts[s["key"]], prev), 2) if prev else None,
                "dropoff_count": (prev - counts[s["key"]]) if prev else None,
            })
        leaks = [s for s in steps if s["dropoff_count"] is not None]
        biggest = max(leaks, key=lambda s: s["dropoff_count"]) if leaks else None
        worst = max(leaks, key=lambda s: s["step_dropoff_pct"]) if leaks else None
        bottom_key = self.stages[-1]["key"]
        return {
            "funnel_name": self.funnel_name,
            "totals": counts,
            "steps": steps,
            "overall_conversion_pct": _pct(counts[bottom_key], counts[self.stages[0]["key"]]),
            "biggest_leak_by_volume": biggest["stage"] if biggest else None,
            "biggest_leak_count": biggest["dropoff_count"] if biggest else None,
            "worst_conversion_step": worst["stage"] if worst else None,
            "worst_conversion_dropoff_pct": worst["step_dropoff_pct"] if worst else None,
        }

    def time_between(self, rows: list[dict]) -> dict:
        out = {}
        for a, b in zip(self.stages, self.stages[1:]):
            deltas = []
            for r in rows:
                ta, tb = parse_ts(r.get(a["ts_column"])), parse_ts(r.get(b["ts_column"]))
                if ta and tb and tb >= ta:
                    deltas.append((tb - ta).total_seconds() / 3600.0)
            if deltas:
                out[f"{a['label']} -> {b['label']}"] = {
                    "median_hours": round(statistics.median(deltas), 1),
                    "mean_hours": round(statistics.mean(deltas), 1),
                    "p90_hours": round(sorted(deltas)[int(0.9 * len(deltas)) - 1], 1),
                    "n": len(deltas),
                }
        return out

    def segment(self, rows: list[dict], dim: str) -> list[dict]:
        if not rows or dim not in rows[0]:
            return []
        groups: dict[str, list[dict]] = {}
        for r in rows:
            groups.setdefault(r.get(dim) or "Unknown", []).append(r)
        top_key = self.stages[0]["key"]
        bottom_key = self.stages[-1]["key"]
        res = []
        for k, grp in groups.items():
            c = self._counts(grp)
            res.append({
                "value": k,
                "top": c[top_key],
                "bottom": c[bottom_key],
                "overall_conversion_pct": _pct(c[bottom_key], c[top_key]),
            })
        return sorted(res, key=lambda x: x["top"], reverse=True)

    def analyze(self, rows: list[dict]) -> dict:
        segments = {d: self.segment(rows, d) for d in self.segment_dimensions
                    if rows and d in rows[0]}
        return {
            "records": len(rows),
            "funnel": self.build_funnel(rows),
            "timing": self.time_between(rows),
            "segments": segments,
        }

    # ---- self-verification ----
    @staticmethod
    def verify(analysis: dict) -> list[str]:
        """Return a list of problems; empty list = all checks passed."""
        problems = []
        steps = analysis["funnel"]["steps"]
        counts = [s["count"] for s in steps]
        if counts != sorted(counts, reverse=True):
            problems.append("Funnel counts are not monotonically non-increasing.")
        for s in steps:
            if s["step_conversion_pct"] is not None:
                tot = s["step_conversion_pct"] + s["step_dropoff_pct"]
                if abs(tot - 100.0) > 0.5:
                    problems.append(
                        f"{s['stage']}: conversion+dropoff = {tot}, expected 100.")
        for dim, table in analysis["segments"].items():
            seg_top = sum(r["top"] for r in table)
            if seg_top != counts[0]:
                problems.append(
                    f"Segment '{dim}' top counts ({seg_top}) != funnel top ({counts[0]}).")
        return problems
